### ISSUE TITLE
[REFACTOR] getComment 기능

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/comment#1]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

- [x] resolved: #2 

## 리팩토링 개요
DB 분리에 의한 기존 getComment() 코드 수정

## TODO

- [x] SQL문 수정
- [x] getComment 컨트롤러 수정
- [x] index 폴더구조 변경
- [x] index 파일 수정
