### ISSUE TITLE
[REFACTOR] dockerfile, yml 파일 변경

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/comment#10]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- dockerfile, yml 파일 수정

## TODO

- [ ] dockerfile 수정
- [ ] yml 파일 수정
