### ISSUE TITLE
[REFACTOR] yml파일 수정

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/comment#13]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요
- 새롭게 빌드한 comment 이미지 yml파일에 작성

## TODO

- [x] comment.yml 파일 수정
