### ISSUE TITLE
[REFACTOR] getCommentCount API 변경

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/comment#17]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 이런 걸 해야해

## TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
