### ISSUE TITLE
[BUG] 댓글 전체 조회시 하나만 조회됨

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/comment#19]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 버그1: 소비내역에 댓글이 달려있지 않을때 TypeError 발생 -> 예외 처리
- 버그2: 소비내역에 여러개의 댓글이 달려있을때 댓글 한개만 조회되는 에러

## TODO

- [x] getComment 컨트롤러에서 댓글의 개수가 0일경우 예외처리
- [x] 조회한 댓글을 대상으로 반복문을 돌며 사용자의 nickname을 넣어줌
