### ISSUE TITLE
[REFACTOR] 라우터 구조 변경

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/comment#6]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요
- 라우터 구조 변경

## TODO

- [x] routes 내에 comment 디렉토리 생성
